version: '3'
services: 
  app: 
    container_name: pastes
    build: './scraper'
    ports:  
        - '3010:3010'
    # networks: #here
    #     - my-network
    restart: always
  mongo:
    container_name: pastes-mongo
    image: mongo
    ports:
        - '27017:27017'
    restart: always
    # networks: #here
    #     - my-network
  darknet: 
    image: dperson/torproxy
    container_name: tor-proxy
    ports: 
      - '8118:8118'
    expose:
      - 8118
    restart: always
  mongo-express:
    image: mongo-express
    container_name: database-client
    restart: always
    ports:
      - 8081:8081
  front: 
    build: './client'
    ports: 
      - 3000:3000
