GET http://localhost:3010/list HTTP/1.1

###

GET http://localhost:3010/list/delete-all HTTP/1.1

###
GET http://localhost:3010/list/scrape HTTP/1.1
###
GET http://localhost:3010/list/long-polling HTTP/1.1
###
GET http://localhost:3010/ HTTP/1.1